
    window.sidenav = '<div class="accordion" id="accordionExample">';
    window.sidenav +='<div class="accordion-item">';
    window.sidenav +='<h2 class="accordion-header" id="headingOne"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Web Elements</button></h2>';
    window.sidenav +='<div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">';
    window.sidenav +='<div class="accordion-body">';
    window.sidenav +='<ul class="list-group">';
    window.sidenav +='<li class="list-group-item"><a href="hyperlinks.html" class="btn btn-link" >Hyperlinks</a></li>';
    window.sidenav +='<li class="list-group-item"><a href="buttons.html" class="btn btn-link" >Buttons</a></li>';
    window.sidenav +='<li class="list-group-item"><a href="checkbox.html" class="btn btn-link" >Checkboxes</a></li>';
    window.sidenav +='<li class="list-group-item"><a href="tb&ta.html" class="btn btn-link" >Textboxes & Textareas</a></li>';
    window.sidenav +='<li class="list-group-item"><a href="brokenlinks.html" class="btn btn-link" >Broken Links</a></li>';
    window.sidenav +='<li class="list-group-item"><a href="updown.html" class="btn btn-link" >Upload & Download</a></li>';
    window.sidenav +='<li class="list-group-item"><a href="table.html" class="btn btn-link" >Web Table</a></li>';
    window.sidenav +='<li class="list-group-item"><a href="radiobtn.html" class="btn btn-link" >Radio Buttons</a></li>';
    window.sidenav +='<li class="list-group-item"><a href="dynamic.html" class="btn btn-link" >Dynamic Properties</a></li>';
    window.sidenav +='</ul>';
    window.sidenav +='</div>';
    window.sidenav +='</div>';
    window.sidenav +='</div>';
    window.sidenav +='<div class="accordion-item">';
    window.sidenav +='<h2 class="accordion-header" id="headingTwo">';
    window.sidenav +='<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">Web Forms</button>';
    window.sidenav +='</h2>';
    window.sidenav +='<div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">';
    window.sidenav +='<div class="accordion-body">';
    window.sidenav +='<ul class="list-group">';
    window.sidenav +='<li class="list-group-item"><a href="form.html" class="btn btn-link" >Web Form</a></li>';
    window.sidenav +='</ul>';
    window.sidenav +='</div>';
    window.sidenav +='</div>';
    window.sidenav +='</div>';
    window.sidenav +='<div class="accordion-item">';
    window.sidenav +='<h2 class="accordion-header" id="headingThree">';
    window.sidenav +='<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">Web Alerts and Windows + Frames</button>';
    window.sidenav +='</h2>';
    window.sidenav +='<div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">';
    window.sidenav +='<div class="accordion-body">';
    window.sidenav +='<strong>This is the third items accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. Its also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.';
    window.sidenav +='</div>';
    window.sidenav +='</div>';
    window.sidenav +='</div>';
    window.sidenav +='</div>';


